export enum MedicalSegment {
  HEMATOLOGY = 'HEMATOLOGY',
  CLINICAL_CHEMISTRY = 'CLINICAL_CHEMISTRY',
  IMMUNOLOGY = 'IMMUNOLOGY',
  MICROBIOLOGY = 'MICROBIOLOGY',
  MOLECULAR_BIOLOGY = 'MOLECULAR_BIOLOGY',
  BLOOD_BANK = 'BLOOD_BANK'
}
